name: get and cache dependencies
description: |
  This action gets and caches dependencies for a project.
  It uses the `actions/cache` action to cache the dependencies.
  The cache key is based on the hash of the `package.json` file.
  The cache is restored if it exists, otherwise it is created.
inputs:
  caching:
    description: 'whether cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
      - name: Cache dependencies
        if: inputs.caching == 'true'
        id: cache
        uses: actions/cache@v4
        with:
          path:  ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'true'
        run: npm ci
        working-directory: 01+Starting+Project
        shell: bash 
